import { AwsClient, AwsV4Signer } from "aws4fetch";

import { env } from "@/lib/env";

// R2's S3-compatible endpoint. Cloudflare accepts any AWS region for R2 but
// documents "auto" as the canonical choice.
const R2_SERVICE = "s3";
const R2_REGION = "auto";
const DEFAULT_PRESIGNED_URL_EXPIRY_SECONDS = 900; // 15 minutes

type R2Config = {
  accountId: string;
  accessKeyId: string;
  secretAccessKey: string;
  bucket: string;
  publicUrl: string;
};

// Fails loud on misconfiguration rather than silently no-op-ing — the R2
// vars are optional in env.ts's schema (so the app can boot without storage
// configured at all), but any actual call into this module with one missing
// is a deploy/config bug, not a runtime condition to swallow.
function getR2Config(): R2Config {
  const {
    R2_ACCOUNT_ID,
    R2_ACCESS_KEY_ID,
    R2_SECRET_ACCESS_KEY,
    R2_BUCKET,
    R2_PUBLIC_URL,
  } = env;

  const missing = (
    [
      ["R2_ACCOUNT_ID", R2_ACCOUNT_ID],
      ["R2_ACCESS_KEY_ID", R2_ACCESS_KEY_ID],
      ["R2_SECRET_ACCESS_KEY", R2_SECRET_ACCESS_KEY],
      ["R2_BUCKET", R2_BUCKET],
      ["R2_PUBLIC_URL", R2_PUBLIC_URL],
    ] as const
  )
    .filter(([, value]) => !value)
    .map(([name]) => name);

  if (missing.length > 0) {
    throw new Error(
      `R2 storage is not configured: missing ${missing.join(", ")}. ` +
        "Set these in .env.local — see .env.example.",
    );
  }

  return {
    accountId: R2_ACCOUNT_ID!,
    accessKeyId: R2_ACCESS_KEY_ID!,
    secretAccessKey: R2_SECRET_ACCESS_KEY!,
    bucket: R2_BUCKET!,
    publicUrl: R2_PUBLIC_URL!,
  };
}

// Object keys are generated by our own upload code, but may contain "/" as a
// folder-like separator (e.g. "products/<id>/thumbnail.webp") — encode each
// segment individually so the slashes stay literal path separators.
function encodeKey(key: string): string {
  return key.split("/").map(encodeURIComponent).join("/");
}

function objectUrl(config: R2Config, key: string): URL {
  return new URL(
    `https://${config.accountId}.r2.cloudflarestorage.com/${config.bucket}/${encodeKey(key)}`,
  );
}

// @types/node redeclares the global `Uint8Array`'s default type parameter as
// `ArrayBufferLike` (to accommodate `Buffer`), while lib.dom's fetch
// `BodyInit` wants `Uint8Array<ArrayBuffer>` — the two disagree on every
// plain `Uint8Array`/`Buffer` since TS 5.7. Slicing out a fresh, concrete
// `ArrayBuffer` sidesteps the mismatch and matches `BodyInit` unconditionally
// (Buffer.slice's runtime behavior only returns SharedArrayBuffer if the
// source itself is backed by one, which nothing in this module produces).
function toArrayBuffer(bytes: Uint8Array): ArrayBuffer {
  return bytes.buffer.slice(
    bytes.byteOffset,
    bytes.byteOffset + bytes.byteLength,
  ) as ArrayBuffer;
}

function getClient(config: R2Config): AwsClient {
  return new AwsClient({
    accessKeyId: config.accessKeyId,
    secretAccessKey: config.secretAccessKey,
    service: R2_SERVICE,
    region: R2_REGION,
  });
}

// A time-limited URL a browser can PUT directly to, so uploaded bytes never
// round-trip through our server. `contentType` is baked into the signature —
// the caller must send the identical Content-Type header on the PUT, or R2
// rejects it as a signature mismatch. Expiry must be set on the URL's query
// string *before* signing — aws4fetch only defaults X-Amz-Expires (86400s)
// when the param is absent, per its `AwsV4Signer` source.
export async function getPresignedUploadUrl(
  key: string,
  contentType: string,
  expiresInSeconds: number = DEFAULT_PRESIGNED_URL_EXPIRY_SECONDS,
): Promise<string> {
  const config = getR2Config();
  const url = objectUrl(config, key);
  url.searchParams.set("X-Amz-Expires", String(expiresInSeconds));

  const signer = new AwsV4Signer({
    url: url.toString(),
    method: "PUT",
    accessKeyId: config.accessKeyId,
    secretAccessKey: config.secretAccessKey,
    service: R2_SERVICE,
    region: R2_REGION,
    signQuery: true,
    headers: { "content-type": contentType },
  });
  const signed = await signer.sign();
  return signed.url.toString();
}

// Server-side upload — used for the re-upload step after 4.5a's processing
// (the browser's presigned PUT is for the raw original; the derived
// responsive sizes get written here, since they don't exist until our server
// has run sharp over the original).
export async function putObject(
  key: string,
  body: Uint8Array,
  contentType: string,
): Promise<void> {
  const config = getR2Config();
  const client = getClient(config);
  const response = await client.fetch(objectUrl(config, key).toString(), {
    method: "PUT",
    body: toArrayBuffer(body),
    headers: { "content-type": contentType },
  });

  if (!response.ok) {
    throw new Error(
      `R2 putObject failed for key "${key}": ${response.status} ${await response.text()}`,
    );
  }
}

export async function getObject(key: string): Promise<Uint8Array> {
  const config = getR2Config();
  const client = getClient(config);
  const response = await client.fetch(objectUrl(config, key).toString(), {
    method: "GET",
  });

  if (!response.ok) {
    throw new Error(
      `R2 getObject failed for key "${key}": ${response.status} ${await response.text()}`,
    );
  }

  return new Uint8Array(await response.arrayBuffer());
}

// R2_PUBLIC_URL points at the bucket's public custom domain (see
// specs/07-security-legal.md: images are served "from a separate origin") —
// this is what gets stored on `product_images.url`, not the R2 API endpoint.
export function publicUrlForKey(key: string): string {
  const { publicUrl } = getR2Config();
  return `${publicUrl.replace(/\/$/, "")}/${encodeKey(key)}`;
}
